version: '3.8'

services:
  astrometry-api:
    build: .
    container_name: astrometry-api
    ports:
      - "5000:5000"
    volumes:
      - ./astrometry_cache:/app/astrometry_cache
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
